App\Domain\Product:
  type: entity
  table: product
  id:
    id:
      type: App\Infrastructure\Orm\ProductIdType
      generator:
        strategy: SEQUENCE
  fields:
    name:
      type: string
      length: 255
    description:
      type: string
      nullable: true
      length: 255
    price:
      type: float
